### ISSUE TITLE
What slice_size is good?

### ISSUE THREAD

**Issue by tari3x** [besport/ocaml-quadtree#1]
Do you have any recommendations?

**Comment by hhugo** [comment]
I don't remember much about this codebase. slice_size represent the maximum number of elements inside a bucket before splitting it again. Large slice_size means that you'll have traverse (List.fold) the entire large bucket even if you care about a small subset. Random guess, I'd try 100 or 1000.

**Comment by tari3x** [comment]
On another thought, I suppose this depends on the size of your search results. If you expect to find 5 points in your typical rectangle, having to sift through 1000 points to get those seems crazy, but if you typical query returns a million points then that seems fine.
