### ISSUE TITLE
Difference between tail-recursive and non-tail-recursive insert

### ISSUE THREAD

**Issue by tari3x** [besport/ocaml-quadtree#2]
Another request for comment: when would I prefer to use the non-tail version?

**Comment by hhugo** [comment]
I don't remember but I can guess that the tail-recursive insert was added to to work better with js_of_ocaml.
I suspect that this only matters for large depth (the default seems to be 15).

**Comment by tari3x** [comment]
Thanks, I guess I'll only use the tail-recursive version!
